#ifndef LITL_MATH_FAST_RNG_H__
#define LITL_MATH_FAST_RNG_H__

#include <cstdint>
#include "litl-core/impl.hpp"

namespace LITL::Math
{
    /// <summary>
    /// Wrapper over a smple multiplicative congruential PRNG.
    /// </summary>
    class FastRng
    {
    public:

        FastRng();
        explicit FastRng(uint_fast32_t seed);
        ~FastRng();

        /// <summary>
        /// Alias for ::next.
        /// </summary>
        /// <returns></returns>
        [[nodiscard]] uint_fast32_t operator()() noexcept;

        /// <summary>
        /// Generates the next random value on the range [::min(), ::max()].
        /// </summary>
        /// <returns></returns>
        [[nodiscard]] uint_fast32_t next() noexcept;

        /// <summary>
        /// Advances the PRNG the specified number of steps.
        /// Equivalent to calling ::next a number of times and discarding the result(s).
        /// </summary>
        /// <param name="steps"></param>
        void discard(uint32_t steps = 1) noexcept;

        /// <summary>
        /// Sets the internal PRNG seed based on time.
        /// </summary>
        void seed() noexcept;

        /// <summary>
        /// Sets the internal PRNG seed to the specified value.
        /// </summary>
        /// <param name="seed"></param>
        void seed(uint_fast32_t seed) noexcept;

        /// <summary>
        /// Returns the minimum value that can be generated by ::next.
        /// </summary>
        /// <returns></returns>
        [[nodiscard]] uint_fast32_t min() const noexcept;

        /// <summary>
        /// Returns the maximum value that can be generated by ::next.
        /// </summary>
        /// <returns></returns>
        [[nodiscard]] uint_fast32_t max() const noexcept;

        /// <summary>
        /// Returns a thread-specific shared copy of the PRNG.
        /// </summary>
        /// <returns></returns>
        [[nodiscard]] static FastRng& shared() noexcept;

    protected:

    private:

        struct Impl;
        Core::ImplPtr<Impl, 4> m_impl;
    };
}

#endif