#ifndef LITL_MATH_GOOD_RNG_H__
#define LITL_MATH_GOOD_RNG_H__

#include <cstdint>
#include "litl-core/impl.hpp"

namespace litl
{
    /// <summary>
    /// Wrapper over a Mersenne Twister 19937 PRNG.
    /// </summary>
    class RandomMT19937
    {
    public:

        RandomMT19937();
        explicit RandomMT19937(uint_fast32_t seed);
        ~RandomMT19937();

        /// <summary>
        /// Alias for ::next.
        /// </summary>
        /// <returns></returns>
        uint_fast32_t operator()() noexcept;

        /// <summary>
        /// Generates the next random value on the range [0, ::max()].
        /// </summary>
        /// <returns></returns>
        [[nodiscard]] uint_fast32_t next() noexcept;

        /// <summary>
        /// Generates the next random value on the range [0, max)
        /// </summary>
        /// <param name="max"></param>
        /// <returns></returns>
        [[nodiscard]] uint_fast32_t next(uint_fast32_t max) noexcept;

        /// <summary>
        /// Generates a random float on the range [0, 1].
        /// The returned float will have up to 6 digits of precision.
        /// </summary>
        /// <returns></returns>
        [[nodiscard]] float next01() noexcept;

        /// <summary>
        /// Advances the PRNG the specified number of steps.
        /// Equivalent to calling ::next a number of times and discarding the result(s).
        /// </summary>
        /// <param name="steps"></param>
        void discard(uint32_t steps = 1) noexcept;

        /// <summary>
        /// Sets the internal PRNG seed based on time.
        /// </summary>
        void seed() noexcept;

        /// <summary>
        /// Sets the internal PRNG seed to the specified value.
        /// </summary>
        /// <param name="seed"></param>
        void seed(uint_fast32_t seed) noexcept;

        /// <summary>
        /// Retrieves the current seed value.
        /// </summary>
        /// <returns></returns>
        [[nodiscard]] uint32_t getSeed() const noexcept;

        /// <summary>
        /// Returns the minimum value that can be generated by ::next.
        /// </summary>
        /// <returns></returns>
        [[nodiscard]] uint_fast32_t min() const noexcept;

        /// <summary>
        /// Returns the maximum value that can be generated by ::next.
        /// </summary>
        /// <returns></returns>
        [[nodiscard]] uint_fast32_t max() const noexcept;

        /// <summary>
        /// Returns a thread-specific shared copy of the PRNG.
        /// </summary>
        /// <returns></returns>
        [[nodiscard]] static RandomMT19937& shared() noexcept;

    protected:

    private:

        struct Impl;
        ImplPtr<Impl, 5004> m_impl;
    };
}

#endif